grafana:
  enabled: true
  adminPassword: admin
  service:
    type: NodePort
    port: 80
    targetPort: 3000
    nodePort: 32000

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true