apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: backend
    component: api
  name: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  strategy:
    blueGreen:
      autoPromotionEnabled: true
      autoPromotionSeconds: 30
      activeService: service-stable
      previewService: service-canary
  template:
    metadata:
      labels:
        app: backend
        component: api
    spec:
      containers:
        - image: mquang279/demo-backend:latest
          name: demo-backend
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
