apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: backend
    component: api
  name: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
      component: api
  strategy:
    canary:
      stableService: backend-stable
      canaryService: backend-canary
      steps:
        - setWeight: 20
        - pause:
            duration: 20s
        - analysis:
            templates:
              - templateName: backend-error-rate
        - setWeight: 50
        - pause:
            duration: 60s
        - analysis:
            templates:
              - templateName: backend-latency
        - setWeight: 100