apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mquang279/demo-app-gitops.git
    targetRevision: release
    path: apps/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: devops-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true