apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/mquang279/demo-app-gitops.git
    targetRevision: main
    path: ci

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true