apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-error-rate
spec:
  metrics:
    - name: backend-error-rate
      interval: 30s
      count: 3
      failureLimit: 1
      successCondition: result[0] < 0.05
      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
          query: |
            (
              sum(rate(http_requests_total{status_code=~"5.."}[1m]))
              /
              sum(rate(http_requests_total[1m]))
            ) or vector(0)