apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-sensor-sa
  namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-sensor-workflow-trigger-role
  namespace: argo-events
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-sensor-workflow-trigger-rolebinding
  namespace: argo-events
subjects:
  - kind: ServiceAccount
    name: ci-sensor-sa
    namespace: argo-events
roleRef:
  kind: Role
  name: ci-sensor-workflow-trigger-role
  apiGroup: rbac.authorization.k8s.io